export const EVENT_TYPES = [
  'Technical', 'Cultural', 'Sports', 'Management', 'Medical',
  'Workshop', 'Academic', 'Social', 'Career',
  'Hackathon', 'Fest', 'Seminar', 'Contest', 'Webinar',
];

export const DISTRICTS = [
  'Online',
  'Mumbai City', 'Mumbai Suburban', 'Thane', 'Palghar', 'Raigad', 'Ratnagiri', 'Sindhudurg',
  'Pune', 'Satara', 'Sangli', 'Kolhapur', 'Solapur',
  'Nashik', 'Dhule', 'Nandurbar', 'Jalgaon',
  'Aurangabad', 'Jalna', 'Beed', 'Latur', 'Osmanabad', 'Nanded', 'Hingoli', 'Parbhani',
  'Nagpur', 'Wardha', 'Yavatmal', 'Amravati', 'Akola', 'Washim', 'Buldhana',
  'Chandrapur', 'Gadchiroli', 'Gondia', 'Bhandara',
];

export const events = [
  {
    id: '1',
    title: 'CodeStorm Hackathon 2025',
    type: 'Hackathon',
    district: 'Pune',
    date: '2025-06-14',
    endDate: '2025-06-15',
    college: 'MIT World Peace University',
    description: 'A 36-hour hackathon open to all Maharashtra engineering students. Build solutions for real-world problems in domains like healthcare, agriculture, and fintech. Prizes worth ₹2,00,000 up for grabs!',
    venue: 'MIT WPU Campus, Kothrud, Pune',
    registrationLink: 'https://example.com/codestorm',
    registrationDeadline: '2025-06-10',
    teamSize: '2-4',
    prize: '₹2,00,000',
    organizer: 'CSE Department, MIT WPU',
    tags: ['AI/ML', 'Web Dev', 'IoT'],
    status: 'approved',
    image: null,
    postedBy: 'user_1',
    createdAt: '2025-05-01',
  },
  {
    id: '2',
    title: 'TechFest Nagpur 2025',
    type: 'Fest',
    district: 'Nagpur',
    date: '2025-07-10',
    endDate: '2025-07-12',
    college: 'VNIT Nagpur',
    description: 'Annual technical festival of VNIT Nagpur featuring competitions, exhibitions, guest lectures, and cultural events. Three days of innovation, learning, and fun!',
    venue: 'VNIT Campus, South Ambazari Road, Nagpur',
    registrationLink: 'https://example.com/techfest',
    registrationDeadline: '2025-07-05',
    teamSize: 'Individual / Team',
    prize: '₹5,00,000 total',
    organizer: 'Students Council, VNIT',
    tags: ['Robotics', 'Gaming', 'Design'],
    status: 'approved',
    image: null,
    postedBy: 'user_2',
    createdAt: '2025-05-03',
  },
  {
    id: '3',
    title: 'AI/ML Seminar Series',
    type: 'Seminar',
    district: 'Online',
    date: '2025-06-20',
    endDate: '2025-06-20',
    college: 'IIT Bombay',
    description: 'A virtual seminar series by IIT Bombay faculty and industry experts covering cutting-edge topics in Artificial Intelligence and Machine Learning — from LLMs to computer vision.',
    venue: 'Online (Zoom)',
    registrationLink: 'https://example.com/aiml-seminar',
    registrationDeadline: '2025-06-18',
    teamSize: 'Individual',
    prize: 'Certificate of Participation',
    organizer: 'CSE Dept, IIT Bombay',
    tags: ['AI', 'ML', 'Deep Learning'],
    status: 'approved',
    image: null,
    postedBy: 'user_3',
    createdAt: '2025-05-05',
  },
  {
    id: '4',
    title: 'Startup Pitch Contest',
    type: 'Contest',
    district: 'Mumbai',
    date: '2025-06-28',
    endDate: '2025-06-28',
    college: 'NMIMS University',
    description: 'Present your startup idea to a panel of investors and industry mentors. Top 3 teams get seed funding and mentorship from Mumbai\'s top entrepreneurs.',
    venue: 'NMIMS Vile Parle Campus, Mumbai',
    registrationLink: 'https://example.com/startup-pitch',
    registrationDeadline: '2025-06-20',
    teamSize: '1-5',
    prize: '₹1,50,000 + Seed Funding',
    organizer: 'E-Cell, NMIMS',
    tags: ['Entrepreneurship', 'Startup', 'Business'],
    status: 'approved',
    image: null,
    postedBy: 'user_4',
    createdAt: '2025-05-07',
  },
  {
    id: '5',
    title: 'Web Dev Workshop: React & Node',
    type: 'Workshop',
    district: 'Pune',
    date: '2025-06-07',
    endDate: '2025-06-08',
    college: 'Symbiosis Institute of Technology',
    description: 'A hands-on 2-day workshop covering full-stack development with React and Node.js. Learn to build production-grade apps with modern tooling. Laptops required.',
    venue: 'SIT Campus, Lavale, Pune',
    registrationLink: 'https://example.com/webdev-workshop',
    registrationDeadline: '2025-06-04',
    teamSize: 'Individual',
    prize: 'Certificate + Goodies',
    organizer: 'CodeClub, SIT',
    tags: ['React', 'Node.js', 'Full Stack'],
    status: 'approved',
    image: null,
    postedBy: 'user_1',
    createdAt: '2025-05-08',
  },
  {
    id: '6',
    title: 'Cyber Security CTF Challenge',
    type: 'Contest',
    district: 'Nashik',
    date: '2025-07-05',
    endDate: '2025-07-06',
    college: 'K.K. Wagh Institute of Engineering',
    description: 'Capture The Flag competition for cybersecurity enthusiasts. Categories include web exploitation, reverse engineering, cryptography, and forensics.',
    venue: 'K.K. Wagh Campus, Nashik',
    registrationLink: 'https://example.com/ctf-nashik',
    registrationDeadline: '2025-07-01',
    teamSize: '2-3',
    prize: '₹75,000',
    organizer: 'CyberSec Club, K.K. Wagh',
    tags: ['Cybersecurity', 'CTF', 'Ethical Hacking'],
    status: 'approved',
    image: null,
    postedBy: 'user_5',
    createdAt: '2025-05-10',
  },
  {
    id: '7',
    title: 'DataThon 2025',
    type: 'Hackathon',
    district: 'Aurangabad',
    date: '2025-07-19',
    endDate: '2025-07-20',
    college: 'MGM College of Engineering',
    description: 'A data science hackathon where teams analyze real datasets provided by industry partners. Best insights win! Open to BE/BTech students across Maharashtra.',
    venue: 'MGM Campus, Aurangabad',
    registrationLink: 'https://example.com/datathon',
    registrationDeadline: '2025-07-14',
    teamSize: '2-4',
    prize: '₹1,00,000',
    organizer: 'Data Science Club, MGM',
    tags: ['Data Science', 'Analytics', 'Python'],
    status: 'approved',
    image: null,
    postedBy: 'user_2',
    createdAt: '2025-05-12',
  },
  {
    id: '8',
    title: 'Design Thinking Bootcamp',
    type: 'Workshop',
    district: 'Kolhapur',
    date: '2025-06-21',
    endDate: '2025-06-22',
    college: 'Shivaji University',
    description: 'Learn design thinking methodology from industry practitioners. Work on real problem statements, ideate, prototype, and present your solutions.',
    venue: 'Shivaji University Campus, Kolhapur',
    registrationLink: 'https://example.com/design-bootcamp',
    registrationDeadline: '2025-06-17',
    teamSize: 'Individual',
    prize: 'Certificate + Portfolio Building',
    organizer: 'Innovation Cell, Shivaji University',
    tags: ['UI/UX', 'Design', 'Innovation'],
    status: 'approved',
    image: null,
    postedBy: 'user_3',
    createdAt: '2025-05-14',
  },
  {
    id: '9',
    title: 'Cloud Computing Webinar',
    type: 'Webinar',
    district: 'Online',
    date: '2025-06-12',
    endDate: '2025-06-12',
    college: 'Savitribai Phule Pune University',
    description: 'Industry experts from AWS, Azure, and GCP discuss the future of cloud computing, serverless architecture, and DevOps best practices.',
    venue: 'Online (Google Meet)',
    registrationLink: 'https://example.com/cloud-webinar',
    registrationDeadline: '2025-06-11',
    teamSize: 'Individual',
    prize: 'Free AWS Credits + Certificate',
    organizer: 'SPPU Tech Community',
    tags: ['Cloud', 'AWS', 'DevOps'],
    status: 'pending',
    image: null,
    postedBy: 'user_6',
    createdAt: '2025-05-15',
  },
  {
    id: '10',
    title: 'Robowar Championship',
    type: 'Contest',
    district: 'Thane',
    date: '2025-08-02',
    endDate: '2025-08-03',
    college: 'RAIT Nerul',
    description: 'Robot battles, line followers, maze solvers — compete across 5 robotics categories. The ultimate robotics showdown in Thane!',
    venue: 'RAIT Campus, Nerul, Navi Mumbai',
    registrationLink: 'https://example.com/robowar',
    registrationDeadline: '2025-07-25',
    teamSize: '2-5',
    prize: '₹1,25,000',
    organizer: 'Robotics Club, RAIT',
    tags: ['Robotics', 'Electronics', 'Engineering'],
    status: 'pending',
    image: null,
    postedBy: 'user_7',
    createdAt: '2025-05-16',
  },
];

export const users = [
  {
    id: 'user_1',
    name: 'Arjun Patil',
    email: 'arjun.patil@mitwpu.edu.in',
    college: 'MIT WPU',
    district: 'Pune',
    role: 'student',
    status: 'approved',
    joinedAt: '2025-04-15',
  },
  {
    id: 'user_2',
    name: 'Sneha Deshmukh',
    email: 'sneha.d@vnit.ac.in',
    college: 'VNIT Nagpur',
    district: 'Nagpur',
    role: 'student',
    status: 'approved',
    joinedAt: '2025-04-18',
  },
  {
    id: 'user_3',
    name: 'Rohan Kulkarni',
    email: 'rohan.k@iitb.ac.in',
    college: 'IIT Bombay',
    district: 'Mumbai',
    role: 'student',
    status: 'approved',
    joinedAt: '2025-04-20',
  },
  {
    id: 'user_4',
    name: 'Priya Sharma',
    email: 'priya.s@nmims.edu',
    college: 'NMIMS',
    district: 'Mumbai',
    role: 'student',
    status: 'approved',
    joinedAt: '2025-04-22',
  },
  {
    id: 'user_5',
    name: 'Rahul More',
    email: 'rahul.m@kkwagh.edu.in',
    college: 'K.K. Wagh Institute',
    district: 'Nashik',
    role: 'student',
    status: 'pending',
    joinedAt: '2025-05-01',
  },
  {
    id: 'user_6',
    name: 'Anjali Joshi',
    email: 'anjali.j@sppu.ac.in',
    college: 'SPPU',
    district: 'Pune',
    role: 'student',
    status: 'pending',
    joinedAt: '2025-05-05',
  },
  {
    id: 'user_7',
    name: 'Nikhil Sawant',
    email: 'nikhil.s@rait.ac.in',
    college: 'RAIT Nerul',
    district: 'Thane',
    role: 'student',
    status: 'pending',
    joinedAt: '2025-05-10',
  },
];

export const currentUser = {
  id: 'admin_1',
  name: 'Admin User',
  email: 'admin@eventradar.in',
  role: 'admin',
};
